def write_cards():
    cards = [{
        'card_title': 'Hacker',
        'card_skill_1': 'Steal: Take (2) coins from another player',
        'card_skill_2': 'Blocks inspection by Inspector',
        'img_src': '../static/img/hacker.svg'},
        {'card_title': 'Inspector',
            'card_skill_1': 'Inspect: Look at another card, then either return it or force an exchange',
            'card_skill_2': 'Blocks stealing by Hacker',
            'img_src': '../static/img/inspector.svg'},
        {'card_title': 'Athlete',
            'card_skill_1': 'Compete: Take (3) coins from the stash',
            'card_skill_2': 'Blocks other competition by other Athletes',
            'img_src': '../static/img/athlete.svg'},
        {'card_title': 'Hunter',
            'card_skill_1': 'Hunt: Pay (5) coins to take the gun from mantle',
            'card_skill_2': 'Skill cannot be replicated by Scientist',
            'img_src': '../static/img/hunter.svg'},
        {'card_title': 'Scientist',
            'card_skill_1': 'Replicate: Repeat the previous skill used',
            'card_skill_2': 'Blocks research by Professor',
            'img_src': '../static/img/scientist.svg'},
        {'card_title': 'Professor',
            'card_skill_1': 'Research: Pull top card from the deck, use a skill, then return the card',
            'card_skill_2': 'Blocks Hunt by Hunter',
            'img_src': '../static/img/teacher.svg'}]
    return cards
